;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-next-line
        evil-previous-line
        evil-replace
        ))

(setq mc/cmds-to-run-once
      '(
        evil-ret
        helm-M-x
        ))
